name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install
      
    - name: Install zod
      run: pnpm add zod
      
    - name: Install Semgrep
      run: pip install semgrep
      
    - name: Lint
      run: pnpm run lint || true
      
    - name: Build
      run: pnpm run build
      
    - name: Test
      run: pnpm test || true

  semgrep:
    name: Scan with Semgrep
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Semgrep
        run: pip install semgrep
      
      - name: Run Semgrep scan
        run: semgrep --config=auto .
        continue-on-error: true
